### ISSUE TITLE
Readme example not running - due to outdated data call?

### ISSUE THREAD

**Issue by geryan** [matthewkling/windscape#1]
Hello Matthew, thanks for making what looks like a really nice package. Unfortunately, at present the readme example fails downloading the 2015 data:

``` r
library(windscape)
library(rWind)
library(raster)
library(tidyverse)
library(gdistance)

times <- expand.grid(yyyy = 2015, mm = 1:12, dd = c(1, 15), tt = 12)
wd <- pmap(times, wind.dl, lon1 = -120, lon2 = -90, lat1 = 30, lat2 = 50)
#> [1] "2015-01-01"
#> [1] "2015-01-01 12:00:00 downloading..."
#> ERROR: database not found. Please, check server
#>                         connection, date or geographical ranges
#> Error in `pmap()`:
#> ℹ In index: 1.
#> Caused by error:
#> ! object 'tmp' not found
#> Backtrace:
#>      ▆
#>   1. ├─purrr::pmap(times, wind.dl, lon1 = -120, lon2 = -90, lat1 = 30, lat2 = 50)
#>   2. │ └─purrr:::pmap_("list", .l, .f, ..., .progress = .progress)
#>   3. │   ├─purrr:::with_indexed_errors(...)
#>   4. │   │ └─base::withCallingHandlers(...)
#>   5. │   ├─purrr:::call_with_cleanup(...)
#>   6. │   └─rWind (local) .f(...)
#>   7. └─base::.handleSimpleError(`<fn>`, "object 'tmp' not found", base::quote(NULL))
#>   8.   └─purrr (local) h(simpleError(msg, call))
#>   9.     └─cli::cli_abort(...)
#>  10.       └─rlang::abort(...)
```
<sup>Created on 2023-12-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This appears to be because [the data it's requesting](https://pae-paha.pacioos.hawaii.edu/erddap/info/ncep_global/index.html) are currently only available from late 2022 -- late 2023

![image](https://github.com/matthewkling/windscape/assets/4963182/6d129dc4-5fce-4840-8bac-8721995c5f7d)

Changing `times` to match this period works
``` r
library(windscape)
library(rWind)
library(raster)
library(tidyverse)
library(gdistance)

times <- expand.grid(yyyy = 2023, mm = 1:2, dd = c(1), tt = 12)
wd <- pmap(times, wind.dl, lon1 = -120, lon2 = -90, lat1 = 30, lat2 = 50)
#> [1] "2023-01-01"
#> [1] "2023-01-01 12:00:00 downloading..."
#> [1] "2023-02-01"
#> [1] "2023-02-01 12:00:00 downloading..."
head(wd[[1]])
#>                     time lat    lon    ugrd10m      vgrd10m       dir     speed
#> 2441 2023-01-01 12:00:00  50 -120.0  1.5601562 -0.139023440  95.09210 1.5663380
#> 2442 2023-01-01 12:00:00  50 -119.5  0.7701562 -0.149023430 100.95126 0.7844416
#> 2443 2023-01-01 12:00:00  50 -119.0 -0.4798437 -0.009023437 268.92268 0.4799286
#> 2444 2023-01-01 12:00:00  50 -118.5  1.3501562  0.530976530  68.53175 1.4508128
#> 2445 2023-01-01 12:00:00  50 -118.0 -0.1598437  0.530976530 343.24625 0.5545143
#> 2446 2023-01-01 12:00:00  50 -117.5  0.5001562  0.410976560  50.59018 0.6473469
```

<sup>Created on 2023-12-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
(though I'm having some other downstream issues that I'm trying to work though, but may result in another issue post)

**Comment by fmenardo** [comment]
Hi @matthewkling,
I would like to use windscape and I encountered the same wind.dl error described by @geryan above.
I know that this is a problem with the online database accessed by [rwind,](https://github.com/jabiologo/rWind/issues/25) and not a windscape problem, but I was wondering if you found another way to access historical wind data?


Thanks!

**Comment by matthewkling** [comment]
@geryan @fmenardo Thanks for flagging this. To work around the problematic rWind function, I've just added a new `cfsr_dl()` function that instead retrieves hourly wind data from CFSR. The readme has been updated to demonstrate use, and it now runs without error on my end. I'm closing this issue but let me know if you continue to experience issues!
