### ISSUE TITLE
Multiple failure points in `windrose_rasters` and `windrose` using Readme script with 2023 data 

### ISSUE THREAD

**Issue by geryan** [matthewkling/windscape#2]
Hi again Matt, thanks for providing example code. Noting #1 , I'm trying to run the readme with a subset of data from 2023.

This downloads fine, but fails later for several reasons:
``` r
library(windscape)
library(rWind)
library(raster)
library(tidyverse)
library(gdistance)
# library(geosphere) # must be installed but is called with ::

times <- expand.grid(yyyy = 2023, mm = 1:2, dd = c(1, 15), tt = 12)
wd <- pmap(times, wind.dl, lon1 = -120, lon2 = -90, lat1 = 30, lat2 = 50)
#> [1] "2023-01-01"
#> [1] "2023-01-01 12:00:00 downloading..."
#> [1] "2023-02-01"
#> [1] "2023-02-01 12:00:00 downloading..."
#> [1] "2023-01-15"
#> [1] "2023-01-15 12:00:00 downloading..."
#> [1] "2023-02-15"
#> [1] "2023-02-15 12:00:00 downloading..."

# convert to raster stack
u <- wd %>%
  map(select, lon, lat, ugrd10m) %>%
  map(rasterFromXYZ) %>%
  stack()
v <- wd %>%
  map(select, lon, lat, vgrd10m) %>%
  map(rasterFromXYZ) %>%
  stack()
wind <- stack(u, v)

# convert wind time series into a wind conductance raster
conductance <- wind %>%
  windrose_rasters(outfile="windrose.tif", order="uuvv", p=1, overwrite = TRUE) %>% 
  add_coords()
#> Error in .calcTest(x[1:5], fun, na.rm, forcefun, forceapply): cannot use this function
```

Looking into this issue by breaking open `windrose_rasters()`:
```r
# internal windrose_rasters
w <- wind
outfile <- "windrose.tif"
order <- "uuvv"
p <- 1
ncores <- 1

rosefun <- function(x) windrose(x, ...)
wr <- add_res(w)
wr <- add_lat(wr)
wr <- raster::calc(wr, fun = rosefun, forceapply = TRUE, 
                   filename = outfile)
#> Error in .calcTest(x[1:5], fun, na.rm, forcefun, forceapply): cannot use this function
```

This is the failure point above, so let's not look into whether we can run `windrose()` internals without `calc`.

**NB** I'm not sure whether this is barking up the wrong tree and there's something else with `calc` I should be chasing up.
```r
# internal windrose()
x <- wr

lat <- x[1]
res <- x[2]
x <- x[3:length(x)]
uv <- matrix(x, ncol = 2, byrow = F)
weight <- sqrt(uv[, 1]^2 + uv[, 2]^2)^p
dir <- spin90(windscape::direction(uv[, 2], -1 * uv[, 1]))
#> Error in x[x < (-180)] <- x[x < (-180)] + 360: NAs are not allowed in subscripted assignments
# Error in x[x < (-180)] <- x[x < (-180)] + 360 : 
#   NAs are not allowed in subscripted assignments
```

Alter `spin90` to cope with `NA`s and try again
```r
spin90 <- function (x) 
{
  x <- x - 90
  ss <- x < (-180) & !is.na(x)
  x[ss] <- x[ss] + 360
  x
}

dir <- spin90(windscape::direction(uv[, 2], -1 * uv[, 1]))


dir[dir < 0] <- dir[dir < 0] + 360
#> Error in dir[dir < 0] <- dir[dir < 0] + 360: NAs are not allowed in subscripted assignments
# Error in dir[dir < 0] <- dir[dir < 0] + 360 : 
#   NAs are not allowed in subscripted assignments
```

And again alterations to handle `NA`s, and proceed
```r
# alter to cope with NA
dirgr0 <- dir < 0 & !is.na(dir)
dir[dirgr0] <- dir[dirgr0] + 360

#ditto
dir0 <- dir == 0
dir[dir0] <- 360


nc <- cbind(x = c(0, res, res, res, 0, -res, -res, -res), 
            y = c(res, res, 0, -res, -res, -res, 0, res) + lat)
#> Warning in c(res, res, 0, -res, -res, -res, 0, res) + lat: longer object length
#> is not a multiple of shorter object length
#> Error in cbind(x = c(0, res, res, res, 0, -res, -res, -res), y = c(res, : dims [product 10] do not match the length of object [62]
```

`lat` and `res` really don't look like I expected them to:
```r
lat
#>      ugrd10m.1.1.1 ugrd10m.1.1.2 ugrd10m.1.2 ugrd10m.2 ugrd10m.3 ugrd10m.4
#> [1,]            50           0.5    1.560156 -1.263652 -1.595265 0.4292944
#>       vgrd10m.1 vgrd10m.2 vgrd10m.3 vgrd10m.4
#> [1,] -0.1390234  1.907605 0.7322021  1.138027
res
#>      ugrd10m.1.1.1 ugrd10m.1.1.2 ugrd10m.1.2 ugrd10m.2 ugrd10m.3 ugrd10m.4
#> [1,]            50           0.5   0.7701562 0.6763476 0.1147351 0.8092944
#>       vgrd10m.1 vgrd10m.2 vgrd10m.3  vgrd10m.4
#> [1,] -0.1490234  1.737605 -1.467798 -0.5819727
```

Not sure if this is the issue or what. Unsure where to from here.

<sup>Created on 2023-12-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by matthewkling** [comment]
@geryan Very sorry for the slow response, not sure why I didn't see a notification when you first opened this issue. 

I've now provided an alternative data download method as noted in #1.

I think the error at the end of your first code chunk is coming from `overwrite = TRUE`, which isn't a valid argument to windrose_rasters. Try removing that argument, deleting windrose.tif on your machine, and then running that line again.

**Comment by supton77** [comment]
Hi @matthewkling,

I'm trying to run the README example, but running into the same issue as [#1](https://github.com/matthewkling/windscape/issues/1) - specifically `Error in .calcTest`.

I will apologize in advance that my research is conducted in Python, and I haven't done much with R since my masters.

starting from a blank installation of R - using R-studio to install the required packages

```
R version 4.3.3 (2024-02-29) -- "Angel Food Cake"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

> library(windscape)
> library(raster)
> library(tidyverse)
> library(gdistance)
> 
> wind <- cfsr_dl(years = 2010, months = 1:12, days = c(1, 15),
+                 xlim = c(-120, -90) + 360, # shift longitudes to be in [0, 360] range for CFSR
+                 ylim = c(30, 50))

# Loading required package: ncdf4
# Error in `pmap()`:
# ℹ In index: 1.
# Caused by error in `nc_open()`:
# ! could not find function "nc_open"
```
I then installed ncdf4

```
> wind <- cfsr_dl(years = 2010, months = 1:12, days = c(1, 15),
+                 xlim = c(-120, -90) + 360, # shift longitudes to be in [0, 360] range for CFSR
+                 ylim = c(30, 50))
# Loading required package: ncdf4
# ... retrieving CFSR data for 2010-01-01 ...
# ... retrieving CFSR data for 2010-01-15 ...

[removed]

# ... retrieving CFSR data for 2010-12-01 ...
# ... retrieving CFSR data for 2010-12-15 ...

> wind_s <- shift(stack(wind), dx = -360)
> 
> conductance <- windrose_rasters(wind_s, order = "uuvv", p = 1)
# Error in .calcTest(x[1:5], fun, na.rm, forcefun, forceapply) : 
#  cannot use this function
```

Please forgive me if I'm making an obvious R mistake :face_with_spiral_eyes: 

A quick note on my use-case: I am looking to replace the input with a netcdf of ERA5 windfields.

Thanks!

**Comment by matthewkling** [comment]
@supton77 This does not appear to be a mistake on your end. I initially thought it might be an issue with the 2010 CFSR data, since you're using 2010 instead of 2000 as in the readme, but 2010 runs without error on my machine.

One possibility: do you have the `geosphere` package installed? It's used internally to the `calc` call in `windrose_rasters` so could be throwing the error if it's not installed. Looks like I need to formalize the package dependencies to make sure users have all the necessary libraries installed (among other to-dos to get windscape more usable as a legit package).

**Comment by supton77** [comment]
That was it - runs perfectly now!

Thanks for the quick response :1st_place_medal:

**Comment by matthewkling** [comment]
Great! I'm guessing this was the problem for @geryan as well, so I'm closing this issue now. Hopefully commit 01b93ff4d2ef910bcc8174082cd8d979d1143a7b will solve this for others going forward.
